# Generated by Django 3.2.6 on 2021-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docFile',
            field=models.FileField(upload_to='%Y-%m-%d-%H-%M-%S'),
        ),
        migrations.AlterField(
            model_name='document',
            name='videoFile',
            field=models.FileField(upload_to='%Y-%m-%d-%H-%M-%S'),
        ),
    ]
