# Generated by Django 3.2.6 on 2021-08-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0003_rename_datetiemofupload_document_datetimeofupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('helper_id', models.AutoField(primary_key=True, serialize=False)),
                ('helper_audio', models.TextField()),
                ('helper_txt', models.TextField()),
                ('helper_csv', models.TextField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.document')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCapture',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_file', models.TextField()),
                ('helper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineclass.helper')),
            ],
        ),
    ]
