# Generated by Django 3.2.6 on 2021-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0002_auto_20210815_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='helper_audio',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='helper',
            name='helper_csv',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='helper',
            name='helper_txt',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='imagecapture',
            name='img_file',
            field=models.ImageField(upload_to=''),
        ),
    ]
