# Generated by Django 3.2.6 on 2021-08-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0006_helper_helper_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='helper_mix_path',
            field=models.FilePathField(null=True),
        ),
    ]
