# Generated by Django 3.2.6 on 2021-08-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0007_helper_helper_mix_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helper',
            old_name='helper_audio',
            new_name='helper_video',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='helper_mix_path',
        ),
    ]
